# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: cedrazorg
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: api-core-serverless-middy
# "service" is the name of this project. This will also be added to your AWS resource names.
service: api-template-serverless-middy

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  region: us-east-1

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - '@aws-sdk/*'


functions:
  hello:
    handler: src/hello.handler
    events:
      - httpApi:
          path: /
          method: POST
  upload:
    handler: src/upload.handler
    events:
      - httpApi:
          path: /upload
          method: POST
